name: Github action basic

# Triggers the workflow manually from the GitHub Actions tab
on:
  workflow_dispatch:

jobs:
  build:
    name: Build and Retrieve Secrets
    environment: prod
    runs-on: ubuntu-latest  # The type of runner that the job will execute on

    steps:
      # Step 1: Retrieve secrets from Keeper
      - name: Retrieve secrets from Keeper
        id: ksecrets  # This ID will be used to reference outputs from this step
        uses: Keeper-Security/ksm-action@master
        with:
          keeper-secret-config: ${{ secrets.KSM_CONFIG }}  # Secret config needed to access Keeper
          secrets: |-
            ekx4TrqzoYu9_PF7h-zwFw/title > REC_TITLE
            ekx4TrqzoYu9_PF7h-zwFw/type > REC_TYPE
            ekx4TrqzoYu9_PF7h-zwFw/field/login > LOGIN
            ekx4TrqzoYu9_PF7h-zwFw/field/password > PASSWORD
            ekx4TrqzoYu9_PF7h-zwFw/custom_field/Expiration Date > env:ExpirationDate
            ekx4TrqzoYu9_PF7h-zwFw/file/server.crt > file:/tmp/server.crt
            ekx4TrqzoYu9_PF7h-zwFw/file/server.key > file:/tmp/server.key
            GHA Demo: Tomcat Cert/field/login > env:LOGIN2
            GHA Demo: Tomcat Cert/field/password > env:PASSWORD2

      # Step 2: Print and Reverse Step Output Variables
      - name: Print and Reverse Step Output Variables
        run: |
          echo "Record Title is: $(echo '${{ steps.ksecrets.outputs.REC_TITLE }}' | rev)"
          echo "Record Type is: $(echo '${{ steps.ksecrets.outputs.REC_TYPE }}' | rev)"
          echo "Login is: $(echo '${{ steps.ksecrets.outputs.LOGIN }}' | rev)"
          echo "Password is: $(echo '${{ steps.ksecrets.outputs.PASSWORD }}' | rev)"

      # Step 3: Print and Reverse Environment Variables
      - name: Print and Reverse Environment Variables
        run: |
          echo "ExpirationDate is: $(echo '${{ env.ExpirationDate }}' | rev)"
          echo "Login2 is: $(echo '${{ env.LOGIN2 }}' | rev)"
          echo "Password2 is: $(echo '${{ env.PASSWORD2 }}' | rev)"

      # Step 4: Print Reversed File Content
      - name: Print Reversed File Content
        run: |
          ls -lah /tmp
          echo "Contents of /tmp/server.crt:"
          rev /tmp/server.crt
